### ISSUE TITLE
[Feature] Use this provider in EF Core Power Tools

### ISSUE THREAD

**Issue by ErikEJ** [Sielnix/EFCore.Snowflake#14]
I plan to add this provider to EF Core Power Tools reverse enginering tooling - is there anythin special I should be aware of (basically wrapping your in-built scaffolding support)

**Comment by Sielnix** [comment]
I don't think that there's anything special to consider. If you will encounter any bugs, limitations or other things you'd like to share or improve, you're welcome to share it.
