### ISSUE TITLE
Cannot set default value 'FALSE' of type 'System.String' on property 'foo' of type 'System.Nullable'1[System.Boolean]' in entity type 'BAR

### ISSUE THREAD

**Issue by coridrew** [Sielnix/EFCore.Snowflake#2]
The table definition in Snowflake for that is

create or replace TRANSIENT TABLE dbname.schemaname.BAR {
...
FOO BOOLEAN DEFAULT FALSE,
...
}

**Comment by Sielnix** [comment]
Hello @coridrew ,
Could you provide some code in c# that triggers that error?

Best regards

**Comment by coridrew** [comment]
We're scaffolding from the EF CLI like 
`dotnet ef dbcontext scaffold...`
https://learn.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-dbcontext-scaffold

**Comment by Sielnix** [comment]
Thank you @coridrew for your bug report. This issue has been fixed in newest version v8.0.3 of EFCore.Snowflake. Please update your nuget package and verify if it's ok.

**Comment by coridrew** [comment]
Verified - thank you! Adding another I found :)
