### ISSUE TITLE
Default Data Types and Data Models to Use Uppercase Value

### ISSUE THREAD

**Issue by Pieeer1** [Sielnix/EFCore.Snowflake#5]
Currently, when using this package, if your models are not all capitalized or the column/table names are not set to the uppercase values, queries into snowflake fail. 

Here are some current workarounds:

A. simple but bad

for every model, set each property column name to upper. Additionally, set the table names to be completely uppercase.

This is a manual approach and can be tiresome if there are many models

B. Functional

Create an attribute IE: `[SnowflakeModel]`

and apply to all of your domain models IE: `[SnowflakeModel] public class MyDatabaseModel{}`

and then call the following:

```CSharp

        foreach (var type in Assembly.GetExecutingAssembly().GetTypes().Where(x => x.GetCustomAttribute<SnowflakeModelAttribute>() is not null))
        {
            modelBuilder.Entity(type, entity => {
                entity.ToTable(type.Name.ToUpper());

                foreach (var property in entity.Metadata.GetProperties())
                {
                    property.SetColumnName(property.Name.ToUpper());
                }
            
            });
        }
```

In my opinion, this should either be baked in or the optional attribute should be allows as the feature

**Comment by Sielnix** [comment]
Hello @Pieeer1, thank you for your feedback.

Issue, that you are addressing looks like a nice-to-have feature, as most Snowflake tables and columns are named UPPERCASE. I think, that additional extension method in `OnModelCreating` to switch to use uppercase naming by default would be ok. Would that be ok for you?

**Comment by Pieeer1** [comment]
Yeah, either that or documenting the fact that it is default uppercase, and C# naming convention is Pascal. I think the default should allow you to operate without custom logic or bad naming conventions being implemented.

**Comment by Sielnix** [comment]
Added additional description to README.
