### ISSUE TITLE
Support for Case-Insensitive Search when tables were created with Case-Sensitive COLLATE option

### ISSUE THREAD

**Issue by coridrew** [Sielnix/EFCore.Snowflake#8]
In the Snowflake EF lib we're migrating from, to do a case-insensitive search we had to do this (our dba does not set up snowflake tables with case-insensitive on, like it was in the SQL Server we migrated from):

```
const maxMatches = 100;
var searchPattern = $"%{request.SearchTerm}%";
return await _dbContext.TableName
  .Where(r => EF.Functions.Like(EF.Functions.Collate(r.ColumnName, "en-ci") , searchPattern)
  .Take(maxMatches)
  .ToListAsync(cancellationToken);
```

Is it possible to achieve the same ci search on a non-ci table, using this library?

**Comment by coridrew** [comment]
Actually, I think this might already work... I'll reopen if not :)

**Comment by coridrew** [comment]
Confirmed it's an issue. Here's the exception it throws:

> Snowflake.Data.Client.SnowflakeDbException (0x80004005): Error: SQL compilation error:
> 
> syntax error line 3 at position 70 unexpected 'COLLATE'. SqlState: 42000, VendorCode: 1003, QueryId: 01b3a1aa-0b06-07c2-00ec-8d191be89f8f
> 
>    at Snowflake.Data.Core.SFStatement.BuildResultSet(QueryExecResponse response, CancellationToken cancellationToken)
> 
>    at Snowflake.Data.Core.SFStatement.ExecuteAsync(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly, CancellationToken cancellationToken)
> 
>    at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
> 
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
> 
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
> 
>    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
> 
>    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
> 
>    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
> 
>    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
> 
>    …

**Comment by Sielnix** [comment]
Hello @coridrew,

Many thanks for your feedback! This bug has been addressed and fixed in v8.0.4 version of EFCore.Snowflake. Please update the package and verify it.

**Comment by coridrew** [comment]
I think it's ALMOST there! The SQL it generates just needs quotes around the value being passed into the collation field.

for example, I'm passing "en-ci" into c# & the generated sql shows en-ci in the query (no quotes). When I run that it breaks, but adding quotes to the generated query runs fine.

As a sidenote, I don't understand how this works https://github.com/Sielnix/EFCore.Snowflake/blob/054bc85774aa869321521f4c4df66507e653bdb9/test/EFCore.Snowflake.FunctionalTests/Custom/SnowflakeQueryLikeCollateTest.cs#L25 

That's how I'm calling it... hrm

**Comment by Sielnix** [comment]
Hello @coridrew ,

This issue is addressed [here](https://github.com/Sielnix/EFCore.Snowflake/blob/054bc85774aa869321521f4c4df66507e653bdb9/src/EFCore.Snowflake/Query/SnowflakeQuerySqlGenerator.cs#L74) - it has quotes generated. I just have double checked it using official 8.0.4 version and it works. Are you sure, that you upgraded the package to v8.0.4 before testing?
